name: ApplyPilot

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: "Restore ApplyPilot cache"
        required: false
        default: "true"
  schedule:

    - cron: '30 2 * * *'  # 08:00 IST

    - cron: '30 4 * * *'  # 10:00 IST

    - cron: '30 6 * * *'  # 12:00 IST

jobs:
  applypilot:
    runs-on: ubuntu-latest

    container:
      image:  ${{ vars.IMAGE }}
    env:
      LLM_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      LLM_MODEL: google/gemini-2.5-flash-lite #deepseek/deepseek-chat-v3
      LLM_URL: https://openrouter.ai/api/v1
      HOME: /root
      
    steps:
      - name: PreChecks
        run: |
          echo "Current directory:"
          pwd

          echo "HOME=$HOME"

          echo "whoami:"
          whoami
      
          echo ""
          echo "Contents of /root/.applypilot:"
          ls -lah /root/.applypilot || true
      
          echo ""
          echo "Contents of searches.yaml:"
          cat /root/.applypilot/searches.yaml || true

      - name: Restore .applypilot cache
        if: github.event_name == 'schedule' || github.event.inputs.use_cache == 'true'
        uses: actions/cache/restore@v4
        with:
          path: /root/.applypilot
          key: applypilot-state
          restore-keys: |
            applypilot-state

      - name: Directory content check
        run: |

          echo ""
          echo "Contents of /root/.applypilot:"
          ls -lah /root/.applypilot || true
          
          echo "Content of tailored resume"
          ls -lah /root/.applypilot/tailored_resumes || true

          echo "Content of Cover letters"
          ls -lah /root/.applypilot/cover_letters || true

      - name: Doctor
        run: |
          applypilot doctor      

      - name: PreConfigurations 
        continue-on-error: true
        run: |
            playwright install-deps
            playwright install
      
      - name: Discover Jobs
        timeout-minutes: 10
        run: |
          applypilot run discover --workers 8
      
      - name: Enrich Jobs
        timeout-minutes: 20
        run: |
          applypilot run enrich --workers 8
      
      - name: Score Jobs
        timeout-minutes: 30
        run: |
          applypilot run score
      
      - name: Tailor Resumes
        timeout-minutes: 30
        run: |
          applypilot run tailor
      
      - name: Generate Cover Letters
        timeout-minutes: 30
        run: |
          applypilot run cover
      
      - name: Generate PDFs
        timeout-minutes: 10
        run: |
          applypilot run pdf

      - name: Stats and Dashboard generation
        if: always()
        timeout-minutes: 2
        run: |
          echo "Generating applypilot status"
          applypilot status
          echo "Generating applypilot dashboard"
          applypilot dashboard

      - name: Check runner filesystem
        if: always()
        run: |
          pwd
          ls -lah /root
          ls -lah /root/.applypilot || true
          
      - name: Send dashboard to Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -F "content=ApplyPilot Dashboard - Run #${{ github.run_number }}" \
            -F "file=@/root/.applypilot/dashboard.html"
            
      - name: Save cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: /root/.applypilot
          key: applypilot-state-${{ github.run_id }}

      - name: Upload dashboard
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: applypilot-dashboard
          path: /root/.applypilot/dashboard.html
          retention-days: 30

      - name: Upload Resume & Cover letter
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: applypilot-resumes-cover
          path: |
            /root/.applypilot/tailored_resumes
            /root/.applypilot/cover_letters
          retention-days: 30

      - name: Upload .applypilot backup
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: applypilot-data
          path: |
            /root/.applypilot/
            .applypilot/
          retention-days: 30
